/*
 * Copyright (c) 2003-2026 Broad Institute, Inc., Massachusetts Institute of Technology, and Regents of the University of California. All rights reserved.
 */
module org.gsea_msigdb.gsea {
    exports edu.mit.broad.genome;
    exports edu.mit.broad.genome.alg;
    exports edu.mit.broad.genome.alg.distrib;
    exports edu.mit.broad.genome.alg.fdr;
    exports edu.mit.broad.genome.alg.gsea;
    exports edu.mit.broad.genome.alg.markers;
    exports edu.mit.broad.genome.charts;
    exports edu.mit.broad.genome.io;
    exports edu.mit.broad.genome.logging;
    exports edu.mit.broad.genome.math;
    exports edu.mit.broad.genome.models;
    exports edu.mit.broad.genome.objects;
    exports edu.mit.broad.genome.objects.esmatrix.db;
    exports edu.mit.broad.genome.objects.strucs;
    exports edu.mit.broad.genome.parsers;
    exports edu.mit.broad.genome.reports;
    exports edu.mit.broad.genome.reports.api;
    exports edu.mit.broad.genome.reports.pages;
    exports edu.mit.broad.genome.reports.web;
    exports edu.mit.broad.genome.utils;
    exports edu.mit.broad.vdb;
    exports edu.mit.broad.vdb.chip;
    exports edu.mit.broad.vdb.map;
    exports edu.mit.broad.vdb.meg;
    exports edu.mit.broad.cytoscape;
    exports edu.mit.broad.xbench.core.api;
    exports edu.mit.broad.xbench.heatmap;
    exports edu.mit.broad.xbench.prefs;
    exports edu.mit.broad.xbench.tui;
    exports org.broad.gsea.ui;
    exports org.genepattern.data.expr;
    exports org.genepattern.data.matrix;
    exports org.genepattern.gsea;
    exports org.genepattern.heatmap;
    exports org.genepattern.heatmap.image;
    exports org.genepattern.io;
    exports org.genepattern.io.expr;
    exports org.genepattern.io.expr.cls;
    exports org.genepattern.io.expr.gct;
    exports org.genepattern.io.expr.res;
    exports xapps.gsea;
    exports xtools.api;
    exports xtools.api.param;
    exports xtools.chip2chip;
    exports xtools.gsea;
    exports xtools.munge;
    exports org.gsea_msigdb.gsea.ui.api;
    exports xapps.gsea.fx;
    exports xapps.gsea.fx.shell;
    exports xapps.gsea.fx.params;
    exports xapps.gsea.fx.tui;
    exports xapps.gsea.fx.viewers;

    requires algorithms;
    requires batik.awt.util;
    requires batik.dom;
    requires batik.svggen;
    requires commons.compress;
    requires commons.io;
    requires commons.lang3;
    requires commons.math3;
    requires dom4j.full;
    requires ecs;
    requires edtftpj;
    requires httpclient;
    requires httpcore;
    requires java.datatransfer;
    requires transitive java.desktop;
    requires java.logging;
    requires transitive java.prefs;
    requires java.xml;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires javafx.swing;
    requires javafx.web;
    requires jcommon;
    requires jdk.xml.dom;
    requires jfreechart;
    requires org.jfree.fxgraphics2d;
    requires com.sun.jna;
    requires json.simple;
    requires maven.artifact;
    requires org.slf4j;
    requires org.slf4j.jul;
    requires trove;
    requires ujmp.complete;

    opens xapps.gsea.fx to javafx.graphics;
    opens xapps.gsea.fx.shell to javafx.graphics;
}
